-- MySQL Script generated by MySQL Workbench
-- mar 12 abr 2022 12:14:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiempomaya
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiempomaya
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiempomaya` ;
USE `tiempomaya` ;

-- -----------------------------------------------------
-- Table `tiempomaya`.`Tipo_Elemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiempomaya`.`Tipo_Elemento` (
  `id_tipo_elemento` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_elemento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiempomaya`.`Elemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiempomaya`.`Elemento` (
  `id_elemento` INT NOT NULL,
  `tipo_elemento` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(25) NULL,
  `descripcion` VARCHAR(500) NULL,
  `significado` VARCHAR(150) NULL,
  PRIMARY KEY (`id_elemento`),
  INDEX `FK_tipo_elemento_idx` (`tipo_elemento` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_elemento`
    FOREIGN KEY (`tipo_elemento`)
    REFERENCES `tiempomaya`.`Tipo_Elemento` (`id_tipo_elemento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiempomaya`.`Tipo_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiempomaya`.`Tipo_Usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiempomaya`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiempomaya`.`Usuario` (
  `nombre_usuario` VARCHAR(25) NOT NULL,
  `id_tipo_usuario` INT NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `sexo` INT NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nombre_usuario`),
  INDEX `fk_tipo_usuario_idx` (`id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_usuario`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `tiempomaya`.`Tipo_Usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiempomaya`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiempomaya`.`Comentario` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(25) NOT NULL,
  `contenido` VARCHAR(500) NULL,
  `fecha_hora` DATETIME NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `FK_nombre_usuario_idx` (`nombre_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_nombre_usuario_comentario`
    FOREIGN KEY (`nombre_usuario`)
    REFERENCES `tiempomaya`.`Usuario` (`nombre_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiempomaya`.`Concepto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiempomaya`.`Concepto` (
  `id_concepto` INT NOT NULL AUTO_INCREMENT,
  `palabra` VARCHAR(45) NOT NULL,
  `significado` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_concepto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiempomaya`.`Reaccion_Concepto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiempomaya`.`Reaccion_Concepto` (
  `id_reaccion` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(25) NOT NULL,
  `id_concepto` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `tipo_reaccion` INT NOT NULL,
  PRIMARY KEY (`id_reaccion`),
  INDEX `fk_nombre_usuario_reaccion_idx` (`nombre_usuario` ASC) VISIBLE,
  INDEX `fk_id_concepto_reaccion_idx` (`id_concepto` ASC) VISIBLE,
  CONSTRAINT `fk_nombre_usuario_reaccion`
    FOREIGN KEY (`nombre_usuario`)
    REFERENCES `tiempomaya`.`Usuario` (`nombre_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_concepto_reaccion`
    FOREIGN KEY (`id_concepto`)
    REFERENCES `tiempomaya`.`Concepto` (`id_concepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiempomaya`.`Juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiempomaya`.`Juego` (
  `id_juego` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(25) NOT NULL,
  `punteo` INT NOT NULL,
  `tiempo` TIME NOT NULL,
  `fallos` INT NOT NULL DEFAULT 0,
  `dificultad` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  PRIMARY KEY (`id_juego`),
  INDEX `fk_nombre_usuario_punteo_idx` (`nombre_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_nombre_usuario_juego`
    FOREIGN KEY (`nombre_usuario`)
    REFERENCES `tiempomaya`.`Usuario` (`nombre_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiempomaya`.`Comentario_Concepto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiempomaya`.`Comentario_Concepto` (
  `id_concepto` INT NOT NULL,
  `id_comentario` INT NOT NULL,
  PRIMARY KEY (`id_concepto`, `id_comentario`),
  INDEX `fk_Palabra_has_Comentario_Comentario1_idx` (`id_comentario` ASC) VISIBLE,
  INDEX `fk_Palabra_has_Comentario_Palabra1_idx` (`id_concepto` ASC) VISIBLE,
  CONSTRAINT `fk_Concepto_has_Comentario_Concepto1`
    FOREIGN KEY (`id_concepto`)
    REFERENCES `tiempomaya`.`Concepto` (`id_concepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Concepto_has_Comentario_Comentario1`
    FOREIGN KEY (`id_comentario`)
    REFERENCES `tiempomaya`.`Comentario` (`id_comentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiempomaya`.`Descripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiempomaya`.`Descripcion` (
  `id_descripcion` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario_autor` VARCHAR(25) NOT NULL,
  `id_concepto` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  PRIMARY KEY (`id_descripcion`),
  INDEX `fk_usuario_autor_descripcion_idx` (`nombre_usuario_autor` ASC) VISIBLE,
  INDEX `fk_id_concepto_descripcion_idx` (`id_concepto` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_autor_descripcion`
    FOREIGN KEY (`nombre_usuario_autor`)
    REFERENCES `tiempomaya`.`Usuario` (`nombre_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_concepto_descripcion`
    FOREIGN KEY (`id_concepto`)
    REFERENCES `tiempomaya`.`Concepto` (`id_concepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
